### Sign Up
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "nickname": "booster",
  "email": "boster@gmail.com",
  "password": "Seba2010!",
  "confirmPassword": "Seba2010!"
}

### Sing In

POST http://localhost:4000/auth/signin
Content-Type: application/json

{
  "email": "rada@gmail.com",
  "password": "Seba2010!"
}


### Test
POST http://localhost:4000/social/test
Content-Type: application/json

{
  "authorId": 1,
  "videoId": "r85tLpyvXLw"
}


### Get Posts
GET http://localhost:4000/post/allresponse


### Is Like
POST http://localhost:4000/like/test
Content-Type: application/json

{
  "authorId": 1,
  "videoId": "HSMTApHncjY"
}

### Messages
POST http://localhost:4000/message/add
Content-Type: application/json

{
  "name": "Edgar",
  "email": "mail@user.com",
  "message": "No message here"
}


### All messages
GET http://localhost:4000/message/all

### XVIDEOS
GET https://www.xvideos.com/pornstars-index


### SPANGBANG
GET https://la.spankbang.com/pornstars


### PORNDB
GET http://porn-bokep.com/tag/viendo-porno-lesbico/datastore_search?resource_id=2396aa60-e969-490f-98a0-d69195639a42&q=jones


### PHUB
GET http://www.pornhub.com/view_video.php?viewkey=591533139

### Pornimage
GET https://api.omniinfer.io/v2/progress?task_id=f7b57066-11fb-457d-90c5-c5d657adbaaf
Content-Type: application/json
X-Omni-Key: f7b57066-11fb-457d-90c5-c5d657adbaaf


### PHUB API test
GET http://localhost:4000/phub/models/3