### Sign Up
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "nickname": "radaman",
  "email": "rada@gmail.com",
  "password": "Seba2010!",
  "confirmPassword": "Seba2010!"
}

### Sing In

POST http://localhost:4000/auth/signin
Content-Type: application/json

{
  "email": "rada@gmail.com",
  "password": "Seba2010!"
}


### Test
POST http://localhost:4000/social/test
Content-Type: application/json

{
  "authorId": 1,
  "videoId": "r85tLpyvXLw"
}


### Get Posts
GET http://localhost:4000/post/allpost/X1OiCyAwKzb
Content-Type: application/json

{
  "videoId": "yRqakpnxc6e"
}